# Generated by Django 5.2.10 on 2026-01-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.PositiveIntegerField()),
                ('duration_min', models.PositiveIntegerField()),
                ('airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airportroute', to='routes.airport')),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_node', to='routes.airport')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_node', to='routes.airport')),
            ],
            options={
                'ordering': ['airport__code'],
            },
        ),
    ]
